### ISSUE TITLE
MacBook Pro did not awake from sleep to print a test page

### ISSUE THREAD

**Issue by aostling** [jt70471/InkjetPlumber#11]
This is critical, since the whole point of Inkjet Plumber is to print while being away from computer for an extended period.

**Comment by aostling** [comment]
Now it is working, waking from sleep to print a test page. I think there is a delay, which caused me initially to think it was not working.

**Comment by jt70471** [comment]
Inkjet Plumber won't wake your Mac if it's actually sleeping... This isn't a problem for me because I always have my iMac powered on. I'd like to add this capability, but unfortunately it's not a straight forward thing to do, as it requires root privileges and Inkjet Plumber currently runs without any special privileges.

**Comment by aostling** [comment]
Jeff,

Thanks for explaining the situation so clearly. I now realize that my
MacBook was not asleep, when I assumed it was. Simply closing the lid won't
but it to sleep, nor does selecting sleep from the Apple menu. This may be
because I have Mail and Finder always open, but I have not tested this to
find out. The only way I can *know* it is asleep, it seems, is if Inkjet
Plumber does *not* print on schedule.

I may adopt your procedure, and keep it powered on even when I am gone for
five weeks (on an overseas trip).

Thanks also for the wonderful app.

Allan Ostling
Phoenix
