### ISSUE TITLE
App will not wake Macbook Pro (high sierra)

### ISSUE THREAD

**Issue by DaveRenfroe** [jt70471/InkjetPlumber#13]
Great app, Jeff - thanks.
I have been testing it while at home.   I hope to use it while away on vacation.
Anyway, it is not waking my Macbook Pro (2011) on OS 10.12.6 to automatically print the page.
It will print the page shortly after I wake up the laptop.
I am using a Canon iP8720 with a Samsung laser printer also hooked up through a hub.
Thanks .....  Dave

**Comment by jt70471** [comment]
Hi, you are correct, Inkjet Plumber cannot wake up your mac, but there is a workaround mentioned [here](https://www.dpreview.com/forums/thread/4034035?page=3#forum-post-61223373)...

Just FYI, I wrote Inkjet Plumber because I could not find any other solution out there, but Qimage One is now available, which will probably prevent me from doing any significant updates to Inkjet Plumber in the future.

Qimage One allows you to schedule purge sheets for your printers and it a great program to use for all things printing related. BTW, it also requires that your mac is not sleeping, so no difference between InkjetPlumber and Qimage One in that regard, but there's actually some thought put into the purge sheet it prints vs the Inkjet Plumber approach where a simple nozzle check is exercised, etc.

**Comment by DaveRenfroe** [comment]
Thanks for this, Jeff.
I am testing out Qimage and it looks like it is more than I need.  From what I see it prints a large image that will use quite a bit of ink, so I may still try to do it with Inkjet Plumber and setting up auto wake on the Mac.
Does it not work with OS 10.6?   I want to set it up on my old MacBook Pro.
- Dave
=-=-=-=-=-=-=-=

**Comment by jt70471** [comment]
Qimage can print a half sheet, which obviously uses half the ink and it actually exercises the print head nozzles which undoubtedly does a more thorough job of exercising the print head. Others are using the trick I pointed you to on the DP forums to wake the mac and let Inkjet Plumber do its thing, so you should be able to replicate that. I don't use it, because I leave my iMac running 24x7...

To be honest, I don't know that I've ever tried to run Inkjet Plumber on 10.6... I don't know why it wouldn't work, but haven't tested that either. I am running High Sierra (10.13.x) so I make sure it continues to work on new releases of macOS, etc.

**Comment by DaveRenfroe** [comment]
Thanks, Jeff.
Not to worry - I have decided to just use the Mac “Automator” to make a little app for scheduling a print from a selected file.   I made my own test page using Qimage’s file and added other stuff.   Using the Mac power saver “schedule” settings and making a iCal alarm that opens the app - it seems to work fine.   And I can automatically completely shut down the Mac between.
Best Regards …..  Dave
