### ISSUE TITLE
Support A4 paper

### ISSUE THREAD

**Issue by kyleamadio** [jt70471/InkjetPlumber#16]
Hi can we add support for different paper sizes - here is Australia we have the A series, like A4

**Comment by jt70471** [comment]
Hi Kyle, unfortunately I've stopped updating InkjetPlumber. The misinformation about timed cleaning cycles on Canon was the reason I wrote this utility for Macs, but that has turned out not to be true, so there's really no advantage to using InkjetPlumber.

In fact, I'm a Qimage One user and use their purge sheet instead. You may want to look at Qimage One.

**Comment by kyleamadio** [comment]
Oh gosh - that's interesting - so there is no need to print a test page every few days to keep the head from clogging up?

**Comment by jt70471** [comment]
There's certainly no harm in doing so, but the current thinking is that it won't prevent cleaning cycles on Canon Printers. Pro-100 is not as bad with cleaning cycles as the Pro-1000, but they will still occur whether you print or not.

**Comment by kyleamadio** [comment]
Thanks for the tip, that is good to know - one would have thought that a
regular print would keep the ink in the head fresh though. Wonder if that
is a thing.

Thanks again
