### ISSUE TITLE
Text on Printed Output FYI

### ISSUE THREAD

**Issue by appfollower** [jt70471/InkjetPlumber#5]
![image](https://cloud.githubusercontent.com/assets/20591358/17088671/11c3f82a-51d3-11e6-98b2-241da777908f.jpeg)

**Comment by jt70471** [comment]
Hi Russ, yes, I added this to help me figure out what's going on with someone's usage of Inkjet Plumber. Once I'm confident that it's working as planned I'll either add an option to remove the textual information or remove it altogether.

**Comment by appfollower** [comment]
Jeff:

A window popped up saying there was a new version - 9.2.0 I think. I updated, and now the menu bar does not show the app as being open. When I click on the menu icon nothing happens.  I tried to trash the app from Finder (in AppZapper) and it said the app was open and couldn’t be trashed. I restarted the iMac but still have exactly the same issues. When I tried to force quit, the app didn’t show up as being open.

It seems to be frozen open, but not showing as open in the menu bar (no little black dot beside the icon).

Russ

**Comment by appfollower** [comment]
Jeff:

I was able to force quit from the Activity Monitor. I then trashed the program and redownloaded 9.2.0 and had all the same problems’

Russ

**Comment by jt70471** [comment]
Hi Russ, since I intend Inkjet Plumber to run constantly, version 0.9.2.0 removes Inkjet Plumber from the dock completely, so whether or not it's running, there should not be a dock entry visible.

There should, however, be an icon in the menuBar area (top right of screen typically) where you see the icon. Clicking on the icon should show you a menu like the following:

<img width="732" alt="menubar" src="https://cloud.githubusercontent.com/assets/1010453/17107889/c0611510-5256-11e6-85f9-90b0c21ced78.png">

Do you have an icon in the menuBar area and does anything happen when you click on that icon?

Thanks

**Comment by appfollower** [comment]
Yes, all good and working fine Jeff. Sorry about using dock/menu bar incorrectly.

**Comment by jt70471** [comment]
Not a problem, you're not using it incorrectly, just my lack of documentation or explanation of the changes... :)

I do appreciate you being a beta tester for me!!! Glad to hear the auto-update notification is working as well, there will likely be frequent changes until i feel it's ready for a larger audience.

**Comment by appfollower** [comment]
Well it didn’t wake up.

FYI, my print schedule did update after I woke the computer and the test prints auto generated.

Russ
